extends Node

# Autoloaded sound playback hub. Loads every named WAV from
# assets/sounds/ on startup and pools AudioStreamPlayer voices so we
# don't allocate on each shot. Two flavors of playback:
#
#   play_3d(name, world_pos) — positional, falls off with distance.
#   play_2d(name)            — UI / global, no spatialization.
#
# Names are stable file basenames — every sound below maps 1:1 to
# assets/sounds/<name>.wav. Replace the WAV without changing code.

const SOUNDS_DIR := "res://assets/sounds"
const VOICE_COUNT_3D := 10
const VOICE_COUNT_2D := 3

const SOUND_NAMES := [
    # Carried over from prior project (already-original synths).
    "jump", "land", "land_hard", "hurt", "death", "step", "pause",
    "enemy_squish", "ground_pound",
    # New, generated by tools/gen_sfx.py.
    "sword_swing", "sword_jab", "sword_hit",
    "sword_charge", "sword_charge_ready",
    "spin_attack", "jump_strike",
    "shield_raise", "shield_block", "parry",
    "roll", "pebble_get", "crystal_hit",
    "gate_open", "gate_close",
    "blob_alert", "blob_attack", "blob_die",
    # Ranged weapons + bombs + hookshot.
    "arrow_fire", "arrow_hit_world", "arrow_hit_flesh",
    "seed_fire", "seed_hit",
    "bomb_fuse", "bomb_explode",
    "hookshot_fire", "hookshot_hit", "hookshot_failed_hit", "hookshot_pull",
    # World props + interactions.
    "bush_cut", "rock_break", "door_unlock", "door_close",
    # NPC + UI feedback.
    "npc_talk_blip",
    "menu_select", "menu_confirm", "menu_back",
    # Pickups + revive + meta.
    "heart_get", "heart_container_get", "fairy_revive",
    # Bosses + warp.
    "boss_horn", "boss_clear", "warp_song",
    # Songs (Triglyph Chord system). One whistle pitch per glyph
    # direction in pentatonic D-major (down=D5, left=E5, center=F#5,
    # right=A5, up=B5) so a 5-glyph song reads as a melody. Tux
    # whistles, not hums. `song_learned` is the "got a new song!"
    # sting; `song_play` is the brief two-note shimmer for re-play.
    "song_glyph_up", "song_glyph_down", "song_glyph_left",
    "song_glyph_right", "song_glyph_center",
    "song_learned", "song_play",
    # Ambient loops (3D positional players use them too).
    "amb_day_wind", "amb_night_crickets", "amb_water_lap",
    # Dungeon-item SFX (hammer wind-up + impact, anchor-boot footstep,
    # glim-sight whoosh, mirror reflect ping). Silent-fallback safe —
    # SoundBank skips any name without a matching .wav at startup.
    "hammer_swing", "hammer_strike", "anchor_step",
    "glim_sight_open", "mirror_reflect",
    # Shop UI: open/close panel, successful purchase, "can't afford"
    # buzz. Silent-fallback safe like everything above — SoundBank just
    # skips ids without a matching .wav.
    "shop_open", "shop_close", "shop_buy", "shop_no_money",
]

var _streams: Dictionary = {}
var _voices_3d: Array[AudioStreamPlayer3D] = []
var _voices_2d: Array[AudioStreamPlayer] = []
var _idx_3d: int = 0
var _idx_2d: int = 0


func _ready() -> void:
    for sound_name in SOUND_NAMES:
        var path := "%s/%s.wav" % [SOUNDS_DIR, sound_name]
        # Tolerant load — if Godot's .godot/imported cache is stale or
        # missing (e.g., after deleting .godot/ to clear an unrelated
        # cache), skip the file with a warning instead of throwing.
        if not ResourceLoader.exists(path):
            push_warning("SoundBank: skipping missing %s" % path)
            continue
        var s: AudioStream = load(path)
        if s:
            _streams[sound_name] = s
        else:
            push_warning("SoundBank: failed to load %s" % path)
    for _i in range(VOICE_COUNT_3D):
        var p := AudioStreamPlayer3D.new()
        p.unit_size = 8.0
        p.max_distance = 30.0
        add_child(p)
        _voices_3d.append(p)
    for _i in range(VOICE_COUNT_2D):
        var p2 := AudioStreamPlayer.new()
        add_child(p2)
        _voices_2d.append(p2)


func play_3d(sound_name: String, world_pos: Vector3, pitch_jitter: float = 0.05) -> void:
    var stream: AudioStream = _streams.get(sound_name)
    if not stream or _voices_3d.is_empty():
        return
    var p := _voices_3d[_idx_3d % _voices_3d.size()]
    _idx_3d += 1
    p.stream = stream
    p.global_position = world_pos
    p.pitch_scale = 1.0 + (randf() * 2.0 - 1.0) * pitch_jitter
    p.play()


func play_2d(sound_name: String, pitch_jitter: float = 0.04) -> void:
    var stream: AudioStream = _streams.get(sound_name)
    if not stream or _voices_2d.is_empty():
        return
    var p := _voices_2d[_idx_2d % _voices_2d.size()]
    _idx_2d += 1
    p.stream = stream
    p.pitch_scale = 1.0 + (randf() * 2.0 - 1.0) * pitch_jitter
    p.play()
